---
name: test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Executes pytest
    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: |
        pip install -r dev-requirements.txt
    - name: Run tests
      run: |
        set -o pipefail
        python -m pytest tests/ --cov=main | tee pytest-coverage.txt
    # Report the test coverage on a PR.
    - name: Report test coverage
      if: ${{ always() }}
      uses: coroo/pytest-coverage-commentator@v1.0.2