---
name: commit

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Executes pytest
    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: |
        pip install -r requirements.txt -r dev-requirements.txt -e .
    - name: Run tests
      run: |
        set -o pipefail
        pytest | tee pytest-coverage.txt
    # Report the test coverage on a PR.
    - name: Report test coverage
      if: ${{ always() }}
      uses: coroo/pytest-coverage-commentator@v1.0.2