---
name: commit

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Executes pytest
    steps:
    - uses: actions/checkout@v2
    # No dependencies in this repo, not necessary
    # - name: Install requirements
    #   run: |
    #     pip install -r requirements.txt
    - name: Run tests
      run: |
        set -o pipefail
        pytest | tee pytest-coverage.txt